name: mshnet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Python环境
  - python=3.8
  
  # PyTorch相关（支持CUDA）
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - torchaudio>=0.9.0
  - cudatoolkit=11.8  # 根据您的CUDA版本调整
  
  # 科学计算基础包
  - numpy>=1.21.0
  - scipy>=1.7.0
  
  # 图像处理
  - pillow>=8.3.0
  - scikit-image>=0.18.0
  
  # 进度条
  - tqdm>=4.62.0
  
  # 其他工具
  - pip>=21.0.0
  
  # pip安装的包
  - pip:
    # 如果需要特定版本的包，可以在这里指定
    # - opencv-python>=4.5.0
    # - matplotlib>=3.4.0
    # - tensorboard>=2.7.0
